### PR TITLE
Upgrade to Ruby2.6

### PR DESCRIPTION
**Pull request by kke**
Also changes the version of rubyc to 0.6.0

I compiled [pharos](https://github.com/kontena/pharos-cluster) using this on macOs and it seems to run `pharos up` successfully with it.

### CODE REVIEW

**Comment by kke** [comment]
And for some reason it doesn't compile on travis.

**Comment by kke** [comment]
```
In file included from ./curses.priv.h:325:0,
                 from ../ncurses/lib_gen.c:19:
_32405.c:843:15: error: expected ‘)’ before ‘int’
../include/curses.h:1631:56: note: in definition of macro ‘mouse_trafo’
 #define mouse_trafo(y,x,to_screen) wmouse_trafo(stdscr,y,x,to_screen)
                                                        ^
Makefile:962: recipe for target '../objects/lib_gen.o' failed
make[1]: *** [../objects/lib_gen.o] Error 1
make[1]: *** Waiting for unfinished jobs....
make[1]: Leaving directory '/home/travis/.rubyc-build.risAAN/ncurses/ncurses'
Makefile:113: recipe for target 'all' failed
make: *** [all] Error 2
```

**Comment by kke** [comment]
Pharos binary created with the binaries from the [2.6.0-0.6.0.rc1 release](https://github.com/kontena/ruby-packer/releases/tag/2.6.0-0.6.0.rc1), which were automatically uploaded using the travis github release deployer:  [pharos.gz](https://github.com/kontena/ruby-packer/files/2732769/pharos.gz)

**Review by jakolehm — APPROVED** [review]

**Comment by ghost** [comment]
Hi @jakolehm  @kke ,

I have tried this, and I got the error with the final binary file:

```
$ rubyc-master  -o ./bin/godaddy   ./bin/godaddy.rb 
# <snip>

$ ./bin/godaddy
Traceback (most recent call last):
./bin/godaddy: No such file or directory -- /__enclose_io_memfs__/local/bin/rubyc (LoadError)
```

Can you have a look?

**Comment by ghost** [comment]
I tried to copy the `bin/rubyc` script (from the source) to my local bin directory (where my script `godaddy.rb` is), and I got new weird error:

```
$ ./bin/godaddy
Traceback (most recent call last):
        2: from /__enclose_io_memfs__/local/bin/rubyc:10:in `<main>'
        1: from /__enclose_io_memfs__/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
/__enclose_io_memfs__/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require': cannot load such file -- compiler (LoadError)
```

Let me know if you need any debug information. Thanks a lot.

**Comment by ghost** [comment]
Ops sorry for the noise. The correct command should be

```
$ rubyc-master  -o ./bin/godaddy  bin/godaddy.rb
```

I didn't know that `./bin` is not allowed.

**Comment by kke** [comment]
It may be that the attempt to add ruby 2.6 failed, we had some problems with it failed. Try asking the upstream https://github.com/pmq20/ruby-packer 

We have this fork because there seems to happen very little in the original project :(

**Comment by ghost** [comment]
@kke So far so good. I have compiled `rubyc-master` from your work, and after a lof of fixes of my setup it works perfectly now. I think the documentation lacks something. 

Why don't you send a PR into upstream? I can see they are quite idle though.

**Pull request merged**
